# Generated by Django 4.2.30 on 2026-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('light cloud', 'Light Cloud'), ('sunny yellow', 'Sunny Yellow'), ('mint green', 'Mint Green'), ('soft peach', 'Soft Peach')], default='light cloud', max_length=30)),
            ],
        ),
    ]
